Added an ARRAY mapper for storing Ledgers in the database
The ArrayType mapper stores Java arrays as SQL ARRAYs. This is
currently implemented as a CompositeType.

However there is a problem at runtime that still needs to be solved:

org.hibernate.MappingException: collection index mapping has wrong number of columns